In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
teis_p = pd.read_csv('../data/teis_p.csv')
teis_p

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,Referral Source Type Name,Initial Eligibility,Initial Eligibility Date,Initial IFSP Date,Latest IFSP Date,Exit Reason,Exit Date
0,ET,411812,12/14/2016,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,DCS,NaN,NaN,NaN,NaN,Unable to contact,12/29/2016
1,ET,417398,4/6/2015,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,Parent,Ineligible,5/16/2017,NaN,NaN,Ineligible for Part C,5/16/2017
2,ET,419400,3/4/2016,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,DCS,NaN,NaN,NaN,NaN,Parent decline,6/30/2017
3,ET,397571,5/11/2015,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,Other,Ineligible,6/16/2017,NaN,NaN,Ineligible for Part C,6/16/2017
4,ET,404648,9/23/2015,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,Other,Eligible,8/1/2016,8/16/2016,7/24/2018,618 - Part B eligibility not determined,9/21/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96575,UC,519094,4/10/2020,Macon,Transitional,Eligibility,I,Sherry Roberts-DS,1/12/2022,1/19/2022,PCP,Ineligible,1/31/2022,NaN,NaN,Ineligible for Part C,1/31/2022
96576,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,PCP,Eligible,5/23/2022,5/31/2022,5/31/2022,NaN,NaN
96577,UC,525460,8/27/2019,Sumner,Competitive,Notification,I,Sherry Roberts-DS,3/29/2022,NaN,PCP,NaN,NaN,NaN,NaN,Unable to contact,4/11/2022
96578,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,Parent,NaN,NaN,NaN,NaN,NaN,NaN
96579,UC,514216,2/4/2021,Sumner,Competitive,IFSP,I,Dawn Reed,11/5/2021,11/10/2021,PCP,Eligible,12/1/2021,12/7/2021,12/7/2021,618 - Parent withdraw,2/10/2022

In [3]:
teis_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96580 entries, 0 to 96579
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   POE                        96580 non-null  object
 1   Child ID                   96580 non-null  int64
 2   DOB                        96580 non-null  object
 3   County Name                96576 non-null  object
 4   County SES                 96576 non-null  object
 5   Child Phase                96580 non-null  object
 6   Active                     96580 non-null  object
 7   Service Coordinator        96579 non-null  object
 8   Notification Date          96580 non-null  object
 9   Parent Consent Date        70026 non-null  object
 10  Referral Source Type Name  96580 non-null  object
 11  Initial Eligibility        68221 non-null  object
 12  Initial Eligibility Date   68221 non-null  object
 13  Initial IFSP Date          45493 non-null  object
 14  Latest IFSP Date           44331 non-null  object
 15  Exit Reason                85194 non-null  object
 16  Exit Date                  85194 non-null  object
dtypes: int64(1), object(16)
memory usage: 12.5+ MB

In [4]:
teis_p = teis_p.rename(columns = {'County SES ' : 'County SES'})
teis_p

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,Referral Source Type Name,Initial Eligibility,Initial Eligibility Date,Initial IFSP Date,Latest IFSP Date,Exit Reason,Exit Date
0,ET,411812,12/14/2016,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,DCS,NaN,NaN,NaN,NaN,Unable to contact,12/29/2016
1,ET,417398,4/6/2015,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,Parent,Ineligible,5/16/2017,NaN,NaN,Ineligible for Part C,5/16/2017
2,ET,419400,3/4/2016,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,DCS,NaN,NaN,NaN,NaN,Parent decline,6/30/2017
3,ET,397571,5/11/2015,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,Other,Ineligible,6/16/2017,NaN,NaN,Ineligible for Part C,6/16/2017
4,ET,404648,9/23/2015,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,Other,Eligible,8/1/2016,8/16/2016,7/24/2018,618 - Part B eligibility not determined,9/21/2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96575,UC,519094,4/10/2020,Macon,Transitional,Eligibility,I,Sherry Roberts-DS,1/12/2022,1/19/2022,PCP,Ineligible,1/31/2022,NaN,NaN,Ineligible for Part C,1/31/2022
96576,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,PCP,Eligible,5/23/2022,5/31/2022,5/31/2022,NaN,NaN
96577,UC,525460,8/27/2019,Sumner,Competitive,Notification,I,Sherry Roberts-DS,3/29/2022,NaN,PCP,NaN,NaN,NaN,NaN,Unable to contact,4/11/2022
96578,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,Parent,NaN,NaN,NaN,NaN,NaN,NaN
96579,UC,514216,2/4/2021,Sumner,Competitive,IFSP,I,Dawn Reed,11/5/2021,11/10/2021,PCP,Eligible,12/1/2021,12/7/2021,12/7/2021,618 - Parent withdraw,2/10/2022

In [5]:
teis_c = pd.read_csv('../data/teis_c.csv')
teis_c

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/16,...,1,2016,1,NaN,NaN,8/9/2017,NaN,1,Qtr 1,#REF!
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,1,2016,1,NaN,NaN,7/31/2016,1.0,1,Qtr 1,#REF!
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/16,...,1,2016,1,NaN,NaN,2/5/2019,NaN,1,Qtr 1,#REF!
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/16,...,1,2016,1,NaN,NaN,12/6/2018,NaN,1,Qtr 1,#REF!
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/16,...,1,2016,1,NaN,NaN,4/18/2018,NaN,1,Qtr 1,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,1,2021,1,NaN,NaN,4/7/2024,NaN,4,Qtr 4,#REF!
113252,UC,528534,3/13/2022,Sumner,Competitive,IFSP,A,Robyn Hogan,5/11/2022,5/23/2022,...,1,2021,1,NaN,NaN,3/13/2025,NaN,4,Qtr 4,#REF!
113253,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,1,2021,1,NaN,NaN,1/5/2025,NaN,4,Qtr 4,#REF!
113254,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,...,1,2021,1,NaN,NaN,9/12/2023,NaN,4,Qtr 4,#REF!
113255,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,...,1,2021,1,NaN,NaN,2/8/2025,NaN,4,Qtr 4,#REF!

In [6]:
teis_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113256 entries, 0 to 113255
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   POE                          113256 non-null  object
 1   Child ID                     113256 non-null  int64
 2   DOB                          113256 non-null  object
 3   County Name                  113251 non-null  object
 4   County SES                   113251 non-null  object
 5   Child Phase                  113256 non-null  object
 6   Active                       113256 non-null  object
 7   Service Coordinator          113255 non-null  object
 8   Notification/ Referral Date  113256 non-null  object
 9   Parent Consent Date          58101 non-null   object
 10  Referral Source Type Name    113256 non-null  object
 11  Initial Eligibility          40762 non-null   object
 12  Initial Eligibility Date     40762 non-null   object
 13  Initial IFSP Date            8010 non-null    object
 14  Latest IFSP Date             7983 non-null    object
 15  Exit Reason                  39366 non-null   object
 16  Exit Date                    39366 non-null   object
 17  Fiscal Year                  113256 non-null  object
 18  Notification Month           113256 non-null  object
 19  Tenn Region                  113256 non-null  object
 20  Referral Count               113256 non-null  int64
 21  Evaluation Count             59469 non-null   float64
 22  Eligibility Count            40762 non-null   float64
 23  IFSP Count                   8010 non-null    float64
 24  Service Coordinator Counter  113256 non-null  int64
 25  Fiscal Year.1                113256 non-null  int64
 26  Child Count                  113256 non-null  int64
 27  2012 Child Count             0 non-null       float64
 28  2013 Child Count             0 non-null       float64
 29  third DOB                    113256 non-null  object
 30  Late Referral                2829 non-null    float64
 31  Qtr                          113256 non-null  int64
 32   QTR                         113256 non-null  object
 33  Referral Source Category     113256 non-null  object
dtypes: float64(6), int64(6), object(22)
memory usage: 29.4+ MB

In [7]:
teis_c = teis_c.rename(columns = {'Notification/ Referral Date' : 'Notification Date'})
teis_c

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/16,...,1,2016,1,NaN,NaN,8/9/2017,NaN,1,Qtr 1,#REF!
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,1,2016,1,NaN,NaN,7/31/2016,1.0,1,Qtr 1,#REF!
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/16,...,1,2016,1,NaN,NaN,2/5/2019,NaN,1,Qtr 1,#REF!
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/16,...,1,2016,1,NaN,NaN,12/6/2018,NaN,1,Qtr 1,#REF!
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/16,...,1,2016,1,NaN,NaN,4/18/2018,NaN,1,Qtr 1,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,1,2021,1,NaN,NaN,4/7/2024,NaN,4,Qtr 4,#REF!
113252,UC,528534,3/13/2022,Sumner,Competitive,IFSP,A,Robyn Hogan,5/11/2022,5/23/2022,...,1,2021,1,NaN,NaN,3/13/2025,NaN,4,Qtr 4,#REF!
113253,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,1,2021,1,NaN,NaN,1/5/2025,NaN,4,Qtr 4,#REF!
113254,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,...,1,2021,1,NaN,NaN,9/12/2023,NaN,4,Qtr 4,#REF!
113255,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,...,1,2021,1,NaN,NaN,2/8/2025,NaN,4,Qtr 4,#REF!

In [8]:
teis_pc = pd.merge(teis_p, teis_c,how = 'outer')
teis_pc

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,411812,12/14/2016,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,...,1.0,2016.0,1.0,NaN,NaN,12/14/2019,NaN,2.0,Qtr 2,#REF!
1,ET,417398,4/6/2015,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ET,419400,3/4/2016,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,...,1.0,2016.0,1.0,NaN,NaN,3/4/2019,NaN,4.0,Qtr 4,#REF!
3,ET,397571,5/11/2015,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ET,404648,9/23/2015,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191573,UC,528094,3/17/2022,Warren,At-Risk,Notification,I,Sherry Roberts-DS,5/4/2022,NaN,...,1.0,2021.0,1.0,NaN,NaN,3/17/2025,NaN,4.0,Qtr 4,#REF!
191574,UC,529508,5/21/2022,Sumner,Competitive,Notification,A,Kim Correll,5/27/2022,NaN,...,1.0,2021.0,1.0,NaN,NaN,5/21/2025,NaN,4.0,Qtr 4,#REF!
191575,UC,528651,10/30/2021,White,Transitional,Evaluation,A,Sherry Roberts-DS,5/13/2022,5/18/2022,...,1.0,2021.0,1.0,NaN,NaN,10/30/2024,NaN,4.0,Qtr 4,#REF!
191576,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,1.0,2021.0,1.0,NaN,NaN,4/7/2024,NaN,4.0,Qtr 4,#REF!
191577,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,1.0,2021.0,1.0,NaN,NaN,1/5/2025,NaN,4.0,Qtr 4,#REF!

In [9]:
teis_pc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 191578 entries, 0 to 191577
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   POE                          191578 non-null  object
 1   Child ID                     191578 non-null  int64
 2   DOB                          191578 non-null  object
 3   County Name                  191570 non-null  object
 4   County SES                   191570 non-null  object
 5   Child Phase                  191578 non-null  object
 6   Active                       191578 non-null  object
 7   Service Coordinator          191577 non-null  object
 8   Notification Date            191578 non-null  object
 9   Parent Consent Date          127024 non-null  object
 10  Referral Source Type Name    191578 non-null  object
 11  Initial Eligibility          107265 non-null  object
 12  Initial Eligibility Date     107265 non-null  object
 13  Initial IFSP Date            53185 non-null   object
 14  Latest IFSP Date             51996 non-null   object
 15  Exit Reason                  106768 non-null  object
 16  Exit Date                    106768 non-null  object
 17  Fiscal Year                  113256 non-null  object
 18  Notification Month           113256 non-null  object
 19  Tenn Region                  113256 non-null  object
 20  Referral Count               113256 non-null  float64
 21  Evaluation Count             59469 non-null   float64
 22  Eligibility Count            40762 non-null   float64
 23  IFSP Count                   8010 non-null    float64
 24  Service Coordinator Counter  113256 non-null  float64
 25  Fiscal Year.1                113256 non-null  float64
 26  Child Count                  113256 non-null  float64
 27  2012 Child Count             0 non-null       float64
 28  2013 Child Count             0 non-null       float64
 29  third DOB                    113256 non-null  object
 30  Late Referral                2829 non-null    float64
 31  Qtr                          113256 non-null  float64
 32   QTR                         113256 non-null  object
 33  Referral Source Category     113256 non-null  object
dtypes: float64(11), int64(1), object(22)
memory usage: 51.2+ MB

In [10]:
teis_pc = teis_pc.drop(columns = ['2012 Child Count', '2013 Child Count', 'Service Coordinator Counter', 'Child Count', 'Referral Source Category'])

In [11]:
teis_pc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 191578 entries, 0 to 191577
Data columns (total 29 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   POE                        191578 non-null  object
 1   Child ID                   191578 non-null  int64
 2   DOB                        191578 non-null  object
 3   County Name                191570 non-null  object
 4   County SES                 191570 non-null  object
 5   Child Phase                191578 non-null  object
 6   Active                     191578 non-null  object
 7   Service Coordinator        191577 non-null  object
 8   Notification Date          191578 non-null  object
 9   Parent Consent Date        127024 non-null  object
 10  Referral Source Type Name  191578 non-null  object
 11  Initial Eligibility        107265 non-null  object
 12  Initial Eligibility Date   107265 non-null  object
 13  Initial IFSP Date          53185 non-null   object
 14  Latest IFSP Date           51996 non-null   object
 15  Exit Reason                106768 non-null  object
 16  Exit Date                  106768 non-null  object
 17  Fiscal Year                113256 non-null  object
 18  Notification Month         113256 non-null  object
 19  Tenn Region                113256 non-null  object
 20  Referral Count             113256 non-null  float64
 21  Evaluation Count           59469 non-null   float64
 22  Eligibility Count          40762 non-null   float64
 23  IFSP Count                 8010 non-null    float64
 24  Fiscal Year.1              113256 non-null  float64
 25  third DOB                  113256 non-null  object
 26  Late Referral              2829 non-null    float64
 27  Qtr                        113256 non-null  float64
 28   QTR                       113256 non-null  object
dtypes: float64(7), int64(1), object(21)
memory usage: 43.8+ MB

In [12]:
teis_pc

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Tenn Region,Referral Count,Evaluation Count,Eligibility Count,IFSP Count,Fiscal Year.1,third DOB,Late Referral,Qtr,QTR
0,ET,411812,12/14/2016,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,...,Eastern,1.0,NaN,NaN,NaN,2016.0,12/14/2019,NaN,2.0,Qtr 2
1,ET,417398,4/6/2015,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ET,419400,3/4/2016,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,...,Eastern,1.0,NaN,NaN,NaN,2016.0,3/4/2019,NaN,4.0,Qtr 4
3,ET,397571,5/11/2015,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ET,404648,9/23/2015,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191573,UC,528094,3/17/2022,Warren,At-Risk,Notification,I,Sherry Roberts-DS,5/4/2022,NaN,...,Middle,1.0,NaN,NaN,NaN,2021.0,3/17/2025,NaN,4.0,Qtr 4
191574,UC,529508,5/21/2022,Sumner,Competitive,Notification,A,Kim Correll,5/27/2022,NaN,...,Middle,1.0,NaN,NaN,NaN,2021.0,5/21/2025,NaN,4.0,Qtr 4
191575,UC,528651,10/30/2021,White,Transitional,Evaluation,A,Sherry Roberts-DS,5/13/2022,5/18/2022,...,Middle,1.0,1.0,NaN,NaN,2021.0,10/30/2024,NaN,4.0,Qtr 4
191576,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,Middle,1.0,1.0,NaN,NaN,2021.0,4/7/2024,NaN,4.0,Qtr 4
191577,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,Middle,1.0,1.0,1.0,NaN,2021.0,1/5/2025,NaN,4.0,Qtr 4

In [13]:
teis_pc.value_counts('POE')

POE
ET    33642
GN    33534
MD    28913
SC    24940
FT    19226
UC    15363
SE    14790
NW    10730
SW    10440
dtype: int64

In [14]:
teis_pc.value_counts('County SES')

County SES
Transitional    122397
Competitive      37875
At-Risk          22322
Attainment        4634
Distressed        4342
dtype: int64

In [15]:
teis_pc.value_counts('County Name')

County Name
Shelby        28899
Davidson      18610
Knox          14357
Rutherford     9612
Hamilton       7698
              ...
Perry           175
Clay            163
Van Buren       151
Pickett          90
Moore            86
Length: 95, dtype: int64

In [16]:
teis_pc.value_counts('Service Coordinator')

Service Coordinator
Signal Centers-EEA        12991
Kim Correll               10896
Rebecca Boshers-ES         5990
Jasmine Douglass           5346
Stacia Hall-Admin          4132
                          ...
RaeKenya Walker-DS            1
Sandra Couch - DSS            1
Brenda Rust-DS                1
Stephanie Scott -Admin        1
Jennifer Hodges-SC            1
Length: 441, dtype: int64

In [17]:
teis_pc.value_counts('Referral Source Type Name')

Referral Source Type Name
PCP                              72921
DCS                              40005
Parent                           39653
Hospital                         11564
Dept. of Health                   5901
NICU                              4970
Other                             4343
Other Health Care Provider        3945
Early Head Start/Head Start       1779
Speech Therapist                  1145
PT                                1093
Family and Friends                 926
Foster Parent                      762
Child Care provider                743
Community/Child Find Activity      676
EIRA                               587
NHS                                317
OT                                 143
PICU                                46
LEA                                 27
DHS                                 21
TIPS                                 6
CAPTA                                3
DMRS                                 2
dtype: int64

In [27]:
teis_pc.head(25)

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Referral Count,Evaluation Count,Eligibility Count,IFSP Count,Fiscal Year.1,third DOB,Late Referral,Qtr,QTR,age
0,ET,411812,2016-12-14,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,...,1.0,NaN,NaN,NaN,2016.0,12/14/2019,NaN,2.0,Qtr 2,12/14/2016
1,ET,417398,2015-04-06,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/6/2015
2,ET,419400,2016-03-04,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,...,1.0,NaN,NaN,NaN,2016.0,3/4/2019,NaN,4.0,Qtr 4,3/4/2016
3,ET,397571,2015-05-11,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5/11/2015
4,ET,404648,2015-09-23,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9/23/2015
5,ET,418289,2015-09-23,Knox,Transitional,Eligibility,I,Theresa Bridges-East,5/12/2017,5/16/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9/23/2015
6,ET,407988,2014-02-22,Knox,Transitional,Notification,I,Susan Gass,9/26/2016,NaN,...,1.0,NaN,NaN,NaN,2016.0,2/22/2017,NaN,1.0,Qtr 1,2/22/2014
7,ET,401498,2016-03-12,Knox,Transitional,Eligibility,I,Susan Gass,7/7/2016,7/7/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3/12/2016
8,ET,409028,2016-09-29,Sevier,Transitional,IFSP,I,Tonia Hodsden,10/18/2016,11/1/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9/29/2016
9,ET,388306,2015-01-30,Sevier,Transitional,Eligibility,I,Tonia Hodsden,10/18/2016,10/19/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/30/2015
10,ET,418144,2017-03-22,Roane,Transitional,Notification,I,Kelly Brackney,5/10/2017,NaN,...,1.0,NaN,NaN,NaN,2016.0,3/22/2020,NaN,4.0,Qtr 4,3/22/2017
11,ET,412334,2015-11-18,Jefferson,Transitional,Eligibility,I,Elizabeth Mounts,1/4/2017,1/17/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/18/2015
12,ET,412291,2015-11-18,Jefferson,Transitional,Eligibility,I,Elizabeth Mounts,1/4/2017,1/17/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/18/2015
13,ET,391530,2014-05-02,Knox,Transitional,Eligibility,I,Cathy Taylor,7/22/2016,7/28/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5/2/2014
14,ET,414869,2016-12-06,Knox,Transitional,IFSP,I,Ashley Jackson,2/23/2017,3/20/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/6/2016
15,ET,410616,2016-05-11,Jefferson,Transitional,Notification,I,Elizabeth Mounts,11/18/2016,NaN,...,1.0,NaN,NaN,NaN,2016.0,5/11/2019,NaN,2.0,Qtr 2,5/11/2016
16,ET,416444,2014-10-22,Anderson,Transitional,Notification,I,Susan Gass,3/29/2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10/22/2014
17,ET,409176,2015-01-13,Scott,Distressed,Eligibility,I,Carrie Hutchison,6/12/2017,6/14/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1/13/2015
18,ET,415371,2016-02-03,Union,At-Risk,IFSP,I,Sarah Scott,5/26/2017,6/14/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2/3/2016
19,ET,419192,2017-02-21,Scott,Distressed,Eligibility,I,Carrie Hutchison,5/31/2017,6/14/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2/21/2017
20,ET,415292,2015-06-26,Sevier,Transitional,Notification,I,Andrea Cooper,3/3/2017,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6/26/2015
21,ET,406244,2014-12-05,Knox,Transitional,Screening,I,Tammy Edwards,8/24/2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12/5/2014
22,ET,406128,2015-11-11,Knox,Transitional,Screening,I,Tammy Edwards,8/22/2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/11/2015
23,ET,416810,2015-04-07,Knox,Transitional,Notification,I,Jackie Campbell,4/10/2017,NaN,...,1.0,NaN,NaN,NaN,2016.0,4/7/2018,NaN,4.0,Qtr 4,4/7/2015
24,ET,408351,2015-02-12,Claiborne,At-Risk,Evaluation,I,Diana Burton,1/23/2017,2/21/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2/12/2015

In [19]:
teis_pc['age'] = ''
teis_pc

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Referral Count,Evaluation Count,Eligibility Count,IFSP Count,Fiscal Year.1,third DOB,Late Referral,Qtr,QTR,age
0,ET,411812,12/14/2016,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,...,1.0,NaN,NaN,NaN,2016.0,12/14/2019,NaN,2.0,Qtr 2,
1,ET,417398,4/6/2015,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,ET,419400,3/4/2016,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,...,1.0,NaN,NaN,NaN,2016.0,3/4/2019,NaN,4.0,Qtr 4,
3,ET,397571,5/11/2015,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,ET,404648,9/23/2015,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191573,UC,528094,3/17/2022,Warren,At-Risk,Notification,I,Sherry Roberts-DS,5/4/2022,NaN,...,1.0,NaN,NaN,NaN,2021.0,3/17/2025,NaN,4.0,Qtr 4,
191574,UC,529508,5/21/2022,Sumner,Competitive,Notification,A,Kim Correll,5/27/2022,NaN,...,1.0,NaN,NaN,NaN,2021.0,5/21/2025,NaN,4.0,Qtr 4,
191575,UC,528651,10/30/2021,White,Transitional,Evaluation,A,Sherry Roberts-DS,5/13/2022,5/18/2022,...,1.0,1.0,NaN,NaN,2021.0,10/30/2024,NaN,4.0,Qtr 4,
191576,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,1.0,1.0,NaN,NaN,2021.0,4/7/2024,NaN,4.0,Qtr 4,
191577,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,1.0,1.0,1.0,NaN,2021.0,1/5/2025,NaN,4.0,Qtr 4,

In [20]:
teis_pc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 191578 entries, 0 to 191577
Data columns (total 30 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   POE                        191578 non-null  object
 1   Child ID                   191578 non-null  int64
 2   DOB                        191578 non-null  object
 3   County Name                191570 non-null  object
 4   County SES                 191570 non-null  object
 5   Child Phase                191578 non-null  object
 6   Active                     191578 non-null  object
 7   Service Coordinator        191577 non-null  object
 8   Notification Date          191578 non-null  object
 9   Parent Consent Date        127024 non-null  object
 10  Referral Source Type Name  191578 non-null  object
 11  Initial Eligibility        107265 non-null  object
 12  Initial Eligibility Date   107265 non-null  object
 13  Initial IFSP Date          53185 non-null   object
 14  Latest IFSP Date           51996 non-null   object
 15  Exit Reason                106768 non-null  object
 16  Exit Date                  106768 non-null  object
 17  Fiscal Year                113256 non-null  object
 18  Notification Month         113256 non-null  object
 19  Tenn Region                113256 non-null  object
 20  Referral Count             113256 non-null  float64
 21  Evaluation Count           59469 non-null   float64
 22  Eligibility Count          40762 non-null   float64
 23  IFSP Count                 8010 non-null    float64
 24  Fiscal Year.1              113256 non-null  float64
 25  third DOB                  113256 non-null  object
 26  Late Referral              2829 non-null    float64
 27  Qtr                        113256 non-null  float64
 28   QTR                       113256 non-null  object
 29  age                        191578 non-null  object
dtypes: float64(7), int64(1), object(22)
memory usage: 45.3+ MB

In [21]:
teis_pc['age'] = teis_pc['DOB']
teis_pc.head()

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Referral Count,Evaluation Count,Eligibility Count,IFSP Count,Fiscal Year.1,third DOB,Late Referral,Qtr,QTR,age
0,ET,411812,12/14/2016,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,...,1.0,NaN,NaN,NaN,2016.0,12/14/2019,NaN,2.0,Qtr 2,12/14/2016
1,ET,417398,4/6/2015,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/6/2015
2,ET,419400,3/4/2016,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,...,1.0,NaN,NaN,NaN,2016.0,3/4/2019,NaN,4.0,Qtr 4,3/4/2016
3,ET,397571,5/11/2015,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5/11/2015
4,ET,404648,9/23/2015,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9/23/2015

In [22]:
teis_pc.DOB = pd.to_datetime(teis_pc.DOB)

In [26]:
datetime.date.today()

NameError: name 'datetime' is not defined

In [25]:
teis_pc.age = teis_pc(now - teis_pc['DOB'])
teis_pc.head()

NameError: name 'now' is not defined

In [24]:
teis_pc

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Referral Count,Evaluation Count,Eligibility Count,IFSP Count,Fiscal Year.1,third DOB,Late Referral,Qtr,QTR,age
0,ET,411812,2016-12-14,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,...,1.0,NaN,NaN,NaN,2016.0,12/14/2019,NaN,2.0,Qtr 2,12/14/2016
1,ET,417398,2015-04-06,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4/6/2015
2,ET,419400,2016-03-04,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,...,1.0,NaN,NaN,NaN,2016.0,3/4/2019,NaN,4.0,Qtr 4,3/4/2016
3,ET,397571,2015-05-11,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5/11/2015
4,ET,404648,2015-09-23,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9/23/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191573,UC,528094,2022-03-17,Warren,At-Risk,Notification,I,Sherry Roberts-DS,5/4/2022,NaN,...,1.0,NaN,NaN,NaN,2021.0,3/17/2025,NaN,4.0,Qtr 4,3/17/2022
191574,UC,529508,2022-05-21,Sumner,Competitive,Notification,A,Kim Correll,5/27/2022,NaN,...,1.0,NaN,NaN,NaN,2021.0,5/21/2025,NaN,4.0,Qtr 4,5/21/2022
191575,UC,528651,2021-10-30,White,Transitional,Evaluation,A,Sherry Roberts-DS,5/13/2022,5/18/2022,...,1.0,1.0,NaN,NaN,2021.0,10/30/2024,NaN,4.0,Qtr 4,10/30/2021
191576,UC,528759,2021-04-07,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,1.0,1.0,NaN,NaN,2021.0,4/7/2024,NaN,4.0,Qtr 4,4/7/2021
191577,UC,528430,2022-01-05,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,1.0,1.0,1.0,NaN,2021.0,1/5/2025,NaN,4.0,Qtr 4,1/5/2022

In [35]:
for index, row in teis_pc.iterrows():
    if row['Exit Date'] == str(teis_pc['Exit Date'],str.extract('%m/%d/%%yy')):
        teis_pc.loc[index, 'Exit Date'] = '%m/%d/%%yy'
    else:
       row['Exit Date'] == pd.to_datetime(teis_pc[index,'Exit Date'])

AttributeError: type object 'str' has no attribute 'extract'

In [28]:
teis_pc['Exit Date'] = pd.to_datetime(teis_pc['Exit Date'])

ParserError: year 44560 is out of range: 44560